[[main]]
  identifier = "about"
  name = "关于我"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 2

[[main]]
  identifier = "notes"
  name = "笔记"
  url = "notes"
  weight = 3

